#!/usr/bin/env python3
"""Extract frame-attention heatmaps with selectable production backends.

Decodes video frames at sampled or all captured ``t_idx`` values and writes
``scout_data/sessions/<id>/heatmaps/t_<N>.npy``.

Usage:
    python scripts/extract_section_heatmaps.py --session-id <id>
    python scripts/extract_section_heatmaps.py --session-id <id> --backend deepgaze_msdb --all-frames
    python scripts/extract_section_heatmaps.py --session-id <id> --saliency
    python scripts/extract_section_heatmaps.py --session-id <id> --uniform-heatmap
    python scripts/extract_section_heatmaps.py --session-id <id> --modal
    python scripts/extract_section_heatmaps.py --session-id <id> --modal --force
    python scripts/extract_section_heatmaps.py --session-id <id> --dry-run
    python scripts/extract_section_heatmaps.py --session-id <id> --refresh-sections

Notes on overwrite / provenance:
    - By default an existing t_<N>.npy is reused regardless of source.
    - A real backend overwrites a file generated by ``--uniform-heatmap``
      (i.e., its manifest entry has ``placeholder: true``).
    - ``--force`` unconditionally overwrites any existing file.
    - heatmaps/manifest.json is merged (not replaced) so entries from previous
      runs are preserved unless a new entry for the same t_idx replaces them.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from activation_store import SESSIONS_DIR
from scout_core.heatmap_extract import (
    capture_size_from_manifest,
    extract_heatmap_deepgaze,
    extract_heatmap_modal,
    file_sha256,
    fps_from_manifest,
    read_heatmaps_manifest,
    write_heatmaps_manifest,
)
from scout_core.heatmap_backends import HEATMAP_BACKENDS, resolve_heatmap_backend
from scout_core.dom_intersect import find_nearest_snapshot
from scout_core.section_pipeline import load_section_config, run_section_analytics
from scout_core.section_sampling import attach_sample_timesteps
from scout_core.session_align import find_walkthrough_video
from scout_core.visual_saliency import build_saliency_heatmap

_SECTION_CFG = PROJECT_ROOT / "configs" / "section_analytics.yaml"
_DEEPGAZE_CFG = PROJECT_ROOT / "configs" / "deepgaze_msdb.yaml"


def _resolve_ffmpeg() -> str | None:
    """Return ffmpeg executable: system PATH first, then imageio-ffmpeg bundle."""
    exe = shutil.which("ffmpeg")
    if exe:
        return exe
    try:
        import imageio_ffmpeg

        return imageio_ffmpeg.get_ffmpeg_exe()
    except ImportError:
        return None


def _extract_frame_ffmpeg(video: Path, t_idx: int, fps: float, out_jpg: Path) -> tuple[bool, str]:
    """Extract a single video frame via ffmpeg.

    Returns ``(success, reason)`` where ``reason`` is empty on success or
    a short diagnostic string on failure.
    """
    ffmpeg = _resolve_ffmpeg()
    if ffmpeg is None:
        return False, "ffmpeg_not_installed"
    sec = t_idx / max(fps, 1e-6)
    cmd = [
        ffmpeg, "-y", "-ss", str(sec), "-i", str(video),
        "-frames:v", "1", "-q:v", "2", str(out_jpg),
    ]
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, timeout=60)
        if out_jpg.is_file():
            return True, ""
        return False, "output_file_missing_after_ffmpeg"
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or b"").decode(errors="replace").strip()
        return False, f"ffmpeg_exit_{exc.returncode}: {stderr[-200:]}"
    except subprocess.TimeoutExpired:
        return False, "ffmpeg_timeout"


def _write_uniform_heatmap(path: Path, h: int, w: int) -> None:
    grid = np.linspace(0.1, 1.0, w * h, dtype=np.float32).reshape(h, w)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.save(path, grid)


def _sample_timesteps_from_bundle(
    session_dir: Path,
    explicit: list[int] | None,
) -> list[int]:
    if explicit:
        return sorted(set(explicit))
    bundle_path = session_dir / "analysis_bundle.json"
    if not bundle_path.is_file():
        raise SystemExit("analysis_bundle.json missing — run run_dual_track.py first.")
    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    if bundle.get("section_report"):
        seen: set[int] = set()
        for sec in bundle["section_report"]:
            for t in sec.get("sample_t_indices") or []:
                seen.add(int(t))
        for tr in bundle.get("grounding_triggers") or []:
            seen.add(int(tr["t_idx"]))
        return sorted(seen)
    cfg = load_section_config(_SECTION_CFG)
    report = run_section_analytics(
        session_dir, bundle, attach_heatmaps=False,
    )
    return sorted(set(attach_sample_timesteps(
        report,
        bundle,
        max_per_section=int(cfg.get("max_samples_per_section", 3)),
        max_total=int(cfg.get("max_heatmaps_per_session", 20)),
    )) | {int(tr["t_idx"]) for tr in bundle.get("grounding_triggers") or []})


def _refresh_section_report(session_dir: Path) -> None:
    bundle_path = session_dir / "analysis_bundle.json"
    if not bundle_path.is_file():
        raise SystemExit("analysis_bundle.json missing — cannot refresh sections.")
    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    report = run_section_analytics(session_dir, bundle, attach_heatmaps=True)
    bundle["section_report"] = report
    bundle_path.write_text(json.dumps(bundle, indent=2), encoding="utf-8")
    print(f"Refreshed section_report ({len(report)} sections) in {bundle_path.name}")


def _load_manifest(session_dir: Path) -> dict[str, Any]:
    manifest_path = session_dir / "session_manifest.json"
    if not manifest_path.is_file():
        return {}
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def _load_deepgaze_config() -> dict[str, Any]:
    if not _DEEPGAZE_CFG.is_file():
        return {}
    with _DEEPGAZE_CFG.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def _resolve_backend(args: argparse.Namespace) -> str:
    legacy = [
        ("uniform", args.uniform_heatmap),
        ("visual_saliency", args.saliency),
        ("modal", args.modal),
    ]
    selected_legacy = [name for name, enabled in legacy if enabled]
    if len(selected_legacy) > 1:
        raise SystemExit("Choose only one legacy backend flag.")
    if selected_legacy:
        selected = selected_legacy[0]
        if args.backend and args.backend != selected:
            raise SystemExit(
                f"--backend {args.backend} conflicts with the legacy flag for {selected}."
            )
        return selected
    try:
        return resolve_heatmap_backend(args.backend)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc


def _all_captured_timesteps(manifest: dict[str, Any]) -> list[int]:
    """Return one timestep for every captured DOM/video sample."""
    snapshots = manifest.get("dom_snapshots") or []
    return sorted({
        int(snapshot.get("t_idx", index))
        for index, snapshot in enumerate(snapshots)
    })


def _load_deepgaze_model(device: str) -> tuple[Any, str, dict[str, Any]]:
    from scout_core.deepgaze_msdb.inference import load_model

    return load_model(device=device, pretrained=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--session-id", required=True)
    parser.add_argument("--timesteps", default=None, help="Comma-separated t_idx list (override sampling)")
    parser.add_argument(
        "--all-frames",
        action="store_true",
        help="Process every captured timestep in session_manifest.json",
    )
    parser.add_argument("--fps", type=float, default=None, help="Override FPS (default from manifest tr_mapping)")
    parser.add_argument("--backend", choices=HEATMAP_BACKENDS, default=None)
    parser.add_argument("--uniform-heatmap", action="store_true", help="Write placeholder heatmaps (no GPU)")
    parser.add_argument("--saliency", action="store_true", help="Write deterministic DOM/visual saliency heatmaps (no GPU)")
    parser.add_argument("--modal", action="store_true", help="Use legacy Modal DINOv2 frame attention")
    parser.add_argument("--force", action="store_true", help="Overwrite all existing heatmaps regardless of source")
    parser.add_argument("--dry-run", action="store_true", help="Extract frames only; do not write heatmaps")
    parser.add_argument("--refresh-sections", action="store_true", help="Re-merge top_elements into analysis_bundle")
    parser.add_argument("--capture-height", type=int, default=None)
    parser.add_argument("--capture-width", type=int, default=None)
    parser.add_argument("--deepgaze-device", choices=["auto", "cpu", "cuda"], default=None)
    parser.add_argument("--pixels-per-degree", type=float, default=None)
    parser.add_argument("--centerbias", choices=["mit1003", "uniform"], default=None)
    parser.add_argument("--max-long-side", type=int, default=None)
    parser.add_argument(
        "--production",
        action="store_true",
        help="Production profile: selected backend + every captured frame",
    )
    args = parser.parse_args(argv)

    if args.production:
        args.all_frames = True

    backend = _resolve_backend(args)
    session_dir = SESSIONS_DIR / args.session_id
    if not session_dir.is_dir():
        raise SystemExit(f"Session not found: {session_dir}")

    if args.refresh_sections:
        _refresh_section_report(session_dir)
        if args.dry_run:
            return

    manifest = _load_manifest(session_dir)
    explicit = None
    if args.timesteps:
        explicit = [int(x.strip()) for x in args.timesteps.split(",") if x.strip()]
    if explicit is not None:
        t_list = sorted(set(explicit))
    elif args.all_frames:
        t_list = _all_captured_timesteps(manifest)
    else:
        t_list = _sample_timesteps_from_bundle(session_dir, None)
    if not t_list:
        print("No timesteps to sample.")
        return

    h, w = capture_size_from_manifest(session_dir)
    if args.capture_height is not None:
        h = args.capture_height
    if args.capture_width is not None:
        w = args.capture_width
    fps = args.fps if args.fps is not None else fps_from_manifest(session_dir)

    use_deepgaze = backend == "deepgaze_msdb" and not args.dry_run
    use_saliency = backend == "visual_saliency" and not args.dry_run
    use_modal = backend == "modal" and not args.dry_run
    use_uniform = backend == "uniform" and not args.dry_run

    heatmaps_dir = session_dir / "heatmaps"
    heatmaps_dir.mkdir(parents=True, exist_ok=True)
    frames_dir = session_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    video = find_walkthrough_video(session_dir)

    # Load existing heatmap manifest for provenance-aware overwrite decisions.
    existing_hm = read_heatmaps_manifest(heatmaps_dir)

    deepgaze_model: Any | None = None
    deepgaze_device = "auto"
    deepgaze_options: dict[str, Any] = {}
    deepgaze_model_meta: dict[str, Any] = {}
    if use_deepgaze:
        from scout_core.deepgaze_msdb.license_notice import license_banner

        dg_cfg = _load_deepgaze_config()
        requested_device = args.deepgaze_device or str(dg_cfg.get("device", "auto"))
        deepgaze_options = {
            "pixels_per_degree": float(
                args.pixels_per_degree
                if args.pixels_per_degree is not None
                else dg_cfg.get("default_pixels_per_degree", 35.0)
            ),
            "centerbias": args.centerbias or str(dg_cfg.get("centerbias", "mit1003")),
            "max_long_side": (
                args.max_long_side
                if args.max_long_side is not None
                else dg_cfg.get("max_long_side")
            ),
        }
        print(license_banner(), file=sys.stderr)
        try:
            deepgaze_model, deepgaze_device, deepgaze_model_meta = _load_deepgaze_model(
                requested_device
            )
        except Exception as exc:
            raise SystemExit(
                "DeepGaze MSDB failed to initialize. Run this stage with the isolated "
                ".venv-deepgaze-msdb interpreter (or configure DEEPGAZE_MSDB_PYTHON). "
                f"Cause: {exc}"
            ) from exc
        print(
            "DeepGaze MSDB loaded once for this session "
            f"(device={deepgaze_device}, source={deepgaze_model_meta.get('source', 'unknown')})."
        )

    hm_entries: list[dict] = []
    n_frames_ok = 0
    n_frames_fail = 0
    n_deepgaze_written = 0
    n_modal_written = 0
    n_saliency_written = 0
    n_placeholder_written = 0
    n_reused = 0
    backend_errors: list[str] = []

    def _process_timestep(t: int, *, modal_inference: Any | None = None) -> None:
        nonlocal n_frames_ok, n_frames_fail, n_deepgaze_written
        nonlocal n_modal_written, n_saliency_written, n_placeholder_written, n_reused

        out_npy = heatmaps_dir / f"t_{t}.npy"
        jpg = frames_dir / f"t_{t}.jpg"

        # Frame extraction
        if video is not None and not jpg.is_file():
            ok, reason = _extract_frame_ffmpeg(video, t, fps, jpg)
            if ok:
                print(f"  t={t}: frame → {jpg.name}")
                n_frames_ok += 1
            else:
                print(f"  t={t}: ffmpeg frame extract failed ({reason})")
                n_frames_fail += 1

        if args.dry_run:
            return

        # Determine if we should overwrite an existing heatmap.
        existing_entry = existing_hm.get(t, {})
        is_placeholder = bool(existing_entry.get("placeholder", False)) or \
                         existing_entry.get("source") == "uniform_placeholder"
        is_orphan_existing = out_npy.is_file() and not existing_entry
        should_overwrite = (
            args.force
            or ((use_deepgaze or use_modal or use_saliency) and is_placeholder)
            or (use_saliency and is_orphan_existing)
        )

        if out_npy.is_file() and not should_overwrite:
            src_label = existing_entry.get("source") or ("placeholder" if is_placeholder else "real")
            print(f"  t={t}: heatmap exists ({src_label}), skip — use --force to overwrite")
            reuse_entry = dict(existing_entry)
            reuse_entry["t_idx"] = t
            if "heatmap_path" not in reuse_entry:
                reuse_entry["heatmap_path"] = out_npy.name
            hm_entries.append(reuse_entry)
            n_reused += 1
            return

        if use_uniform:
            _write_uniform_heatmap(out_npy, h, w)
            print(f"  t={t}: uniform placeholder → {out_npy.name}")
            hm_entries.append({
                "t_idx": t,
                "heatmap_path": out_npy.name,
                "source": "uniform_placeholder",
                "placeholder": True,
            })
            n_placeholder_written += 1
            return

        if not jpg.is_file():
            message = f"t={t}: no frame — add video or use --backend uniform"
            print(f"  {message}")
            backend_errors.append(message)
            return

        if use_deepgaze:
            try:
                density, metadata = extract_heatmap_deepgaze(
                    jpg,
                    h,
                    w,
                    model=deepgaze_model,
                    device=deepgaze_device,
                    **deepgaze_options,
                )
                np.save(out_npy, density)
                print(
                    f"  t={t}: DeepGaze density → {out_npy.name} "
                    f"(sum={float(density.sum(dtype=np.float64)):.6f})"
                )
                provenance = metadata.get("provenance") or {}
                hm_entries.append({
                    "t_idx": t,
                    "frame_path": str(jpg.relative_to(session_dir)),
                    "heatmap_path": out_npy.name,
                    "source": "deepgaze_msdb",
                    "placeholder": False,
                    "sha256": file_sha256(out_npy),
                    "value_semantics": metadata["value_semantics"],
                    "normalization": metadata["normalization"],
                    "density_sum": metadata["density_sum"],
                    "dom_scoring_adapter": metadata["dom_scoring_adapter"],
                    "model_id": provenance.get("model_id"),
                    "license_status": metadata.get("license_status"),
                    "dataset_mode": provenance.get("dataset_mode"),
                    "pixels_per_degree": provenance.get("pixels_per_degree"),
                    "centerbias": provenance.get("centerbias"),
                    "device": provenance.get("device"),
                    "runtime_model": deepgaze_model_meta,
                    "timings": metadata.get("timings"),
                    "warnings": metadata.get("warnings") or [],
                })
                n_deepgaze_written += 1
            except Exception as exc:
                message = f"t={t}: DeepGaze failed ({exc})"
                print(f"  {message}")
                backend_errors.append(message)
            return

        if use_saliency:
            snapshot = find_nearest_snapshot(manifest, int(t))
            if snapshot is None:
                print(f"  t={t}: no DOM snapshot — cannot build saliency heatmap")
                return
            try:
                heatmap, scored = build_saliency_heatmap(jpg, snapshot, capture_h=h, capture_w=w)
                np.save(out_npy, heatmap)
                print(f"  t={t}: saliency heatmap → {out_npy.name} ({len(scored)} elements)")
                hm_entries.append({
                    "t_idx": t,
                    "frame_path": str(jpg.relative_to(session_dir)),
                    "heatmap_path": out_npy.name,
                    "source": "visual_saliency",
                    "placeholder": False,
                    "sha256": file_sha256(out_npy),
                    "n_elements_scored": len(scored),
                })
                n_saliency_written += 1
            except Exception as exc:
                print(f"  t={t}: saliency failed ({exc})")
            return

        if use_modal:
            try:
                heatmap = extract_heatmap_modal(jpg, h, w, inference=modal_inference)
                np.save(out_npy, heatmap)
                print(f"  t={t}: Modal heatmap → {out_npy.name}")
                hm_entries.append({
                    "t_idx": t,
                    "frame_path": str(jpg.relative_to(session_dir)),
                    "heatmap_path": out_npy.name,
                    "source": "modal",
                    "placeholder": False,
                    "sha256": file_sha256(out_npy),
                })
                n_modal_written += 1
            except Exception as exc:
                print(f"  t={t}: Modal failed ({exc}) — use --uniform-heatmap for offline tests")

    if use_modal:
        import modal
        from tribe import TribeInference, app

        with modal.enable_output():
            with app.run():
                inference = TribeInference()
                for t in t_list:
                    _process_timestep(t, modal_inference=inference)
    else:
        for t in t_list:
            _process_timestep(t)

    # Merge into existing manifest so earlier provenance is not lost.
    if hm_entries and not args.dry_run:
        write_heatmaps_manifest(heatmaps_dir, hm_entries, merge=True)

    wrote_real = n_deepgaze_written + n_modal_written + n_saliency_written
    if wrote_real > 0 and (session_dir / "analysis_bundle.json").is_file():
        _refresh_section_report(session_dir)

    # Summary
    print(f"\nSampled {len(t_list)} timestep(s). Heatmaps dir: {heatmaps_dir}")
    if not args.dry_run:
        print(
            f"  backend={backend}  deepgaze={n_deepgaze_written}  modal={n_modal_written}  "
            f"saliency={n_saliency_written}  placeholder_written={n_placeholder_written}"
            f"  reused={n_reused}  frames_ok={n_frames_ok}  frames_fail={n_frames_fail}"
        )
    if use_deepgaze and backend_errors:
        raise SystemExit(
            f"DeepGaze MSDB did not produce every requested frame ({len(backend_errors)} failure(s)); "
            + "; ".join(backend_errors[:3])
        )
    if use_modal and n_modal_written == 0 and not args.dry_run:
        print(
            "WARNING: --modal was requested but zero real heatmaps were produced. "
            "Check that video frames were extracted and Modal is reachable.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
